# Site settings
title: Aissam BELHACHMI
email: edmeral.aissam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Still searching for an original description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aissam.me" # the base hostname & protocol for your site
twitter_username: Edmeral
github_username:  Edmeral

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [footnotes]
exclude: ["node_modules", "gulpfile.js", "package.json"]

gems:
  - jemoji
