# Site settings
title: Aissam BELHACHMI
email: edmeral.aissam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Enthusiastic about everything that ends with dot js. Book worm. 
  Guitar newbie. Enjoys biking in moderate temperatures. 
  I save the world in my spare time.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aissam.me" # the base hostname & protocol for your site
twitter_username: Edmeral
github_username:  Edmeral

# Build settings
markdown: redcarpet
exclude: ["node_modules", "gulpfile.js", "package.json"]